---
management:
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: product-service
          predicates:
            - Path=/api/v1/product
          uri: lb://product-service
        - id: order-service
          predicates:
            - Path=/api/v1/order
          uri: lb://order-service
        - id: inventory-service
          predicates:
            - Path=/api/v1/inventory
          uri: lb://inventory-service
        - id: discovery-server
          predicates:
            - Path=/eureka/web
            - Path=/eureka/**
          uri: http://localhost:8761
          filters:
            - SetPath=/
