spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/spring-micro_product-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0