spring:
  application:
    name: inventory-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-micro_inventory-service
    username: root
    password: pa55w0rd!
  jpa:
    hibernate:
      ddlAuto: validate
management:
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0